### ISSUE TITLE
defineR metadata template

### ISSUE THREAD

**Issue by lexjansen** [dbosak01/defineR#32]
The FAQ at https://definer.r-sassy.org/articles/defineR-faq.html mentions:

Is this the same template as the SAS® toolkit?
Q: This template looks exactly like the template in the SAS® Clinical Standards Toolkit. Are they the same?

A: Yes. The metadata template for the defineR package was taken directly from the SAS® template. This was done for ease of interchange/migration between the two systems.

This is incorrect. Although the metadata content is very similar, the structure of the metadata tables and columns is quite different between CST and defineR.

**Comment by dbosak01** [comment]
Yes, you're right.  I just updated the documentation.  The template was take from the book "Implementing CDISC Using SAS" instead of from the CST.  Will also resubmit my COSA application.

**Comment by lexjansen** [comment]
Aah, yes, I forgot about Holland / Shostak book! Thank you.

**Comment by dbosak01** [comment]
Just resubmitted updated application to COSA, and updated package to CRAN.  Thanks for reminding me of this issue.
